/*
 * NintendulatorML - Localization System
 * src/Lang.h
 */
#pragma once
#include <windows.h>
#include <tchar.h>
#include <map>
#include <vector>
#include <string>

// ============================================================
// STRING IDENTIFIERS - one ID per translatable string
// Add new IDs here, before LANG_STRING_COUNT
// ============================================================
enum LangStringID
{
    // ---------- Main Menu ----------
    LANG_MENU_FILE = 0,
    LANG_MENU_FILE_OPEN,
    LANG_MENU_FILE_CLOSE,
    LANG_MENU_FILE_RECENT,
    LANG_MENU_FILE_RECENT_CLEAR,
    LANG_MENU_FILE_EXIT,
    LANG_MENU_NES,
    LANG_MENU_NES_RUN,
    LANG_MENU_NES_PAUSE,
    LANG_MENU_NES_RESET,
    LANG_MENU_NES_POWER,
    LANG_MENU_NES_STOP,
    LANG_MENU_SETTINGS,
    LANG_MENU_SETTINGS_VIDEO,
    LANG_MENU_SETTINGS_SOUND,
    LANG_MENU_SETTINGS_CONTROLLERS,
    LANG_MENU_SETTINGS_GAMEGENIE,
    LANG_MENU_SETTINGS_PATHS,
    LANG_MENU_SETTINGS_CLOCK,
    LANG_MENU_MOVIE,
    LANG_MENU_MOVIE_RECORD,
    LANG_MENU_MOVIE_PLAY,
    LANG_MENU_MOVIE_STOP,
    LANG_MENU_CPU,
    LANG_MENU_PPU,
    LANG_MENU_SOUND,
    LANG_MENU_INPUT,
    LANG_MENU_DEBUG,
    LANG_MENU_DEBUG_CPU,
    LANG_MENU_DEBUG_PPU,
    LANG_MENU_MISC,
    LANG_MENU_LANGUAGE,
    LANG_MENU_HELP,
    LANG_MENU_HELP_ABOUT,

    // ---------- Window Title ----------
    LANG_WINDOW_TITLE,
    LANG_WINDOW_TITLE_PAUSED,
    LANG_WINDOW_TITLE_FPS,
    LANG_WINDOW_TITLE_STOPPED,
    LANG_WINDOW_TITLE_FPS_NOSKIP,
    LANG_WINDOW_TITLE_FPS_FSKIP,
    LANG_TITLEBAR_AUTO,
    LANG_DLG_VOL_TITLE,

    // ---------- File Open Dialog ----------
    LANG_OPEN_ROM_TITLE,
    LANG_OPEN_ROM_FILTER,
    LANG_OPEN_MOVIE_TITLE,
    LANG_SAVE_MOVIE_TITLE,
    LANG_OPEN_PALETTE_TITLE,
    LANG_SAVE_AVI_TITLE,

    // ---------- NES.cpp - ROM Errors ----------
    LANG_ERR_ROM_OPEN,
    LANG_ERR_ROM_INVALID,
    LANG_ERR_ROM_MAPPER,
    LANG_ERR_ROM_UNIF,
    LANG_ERR_ROM_FDS_HEADER,
    LANG_ERR_ROM_FDS_DISKSIDE,
    LANG_ERR_ROM_NSF,
    LANG_MSG_ROM_LOADED,
    LANG_MSG_ROM_CLOSED,
    LANG_MSG_ROM_ALREADY_LOADED,

    // ---------- GFX.cpp - Video ----------
    LANG_ERR_GFX_DIRECTDRAW,
    LANG_ERR_GFX_SURFACE,
    LANG_ERR_GFX_PALETTE,
    LANG_ERR_GFX_RENDER,
    LANG_ERR_GFX_MODE,
    LANG_MSG_GFX_SCREENSHOT,

    // ---------- APU.cpp - Audio ----------
    LANG_ERR_APU_DIRECTSOUND,
    LANG_ERR_APU_BUFFER,
    LANG_ERR_APU_FORMAT,
    LANG_MSG_APU_DISABLED,

    // ---------- Controllers.cpp ----------
    LANG_ERR_CTRL_KEYBOARD_INIT,
    LANG_ERR_CTRL_KEYBOARD_FORMAT,
    LANG_ERR_CTRL_KEYBOARD_LEVEL,
    LANG_ERR_CTRL_MOUSE_INIT,
    LANG_ERR_CTRL_MOUSE_LEVEL,
    LANG_ERR_CTRL_JOY_LEVEL,
    LANG_ERR_CTRL_INVALID_STD,
    LANG_ERR_CTRL_INVALID_EXP,

    // ---------- States.cpp - Savestates ----------
    LANG_MSG_STATE_SAVED,
    LANG_MSG_STATE_LOADED,
    LANG_ERR_STATE_SAVE,
    LANG_ERR_STATE_LOAD,
    LANG_ERR_STATE_VERSION,
    LANG_ERR_STATE_CORRUPT,
    LANG_MSG_STATE_SLOT,

    // ---------- Movie.cpp - Recording ----------
    LANG_MSG_MOVIE_RECORDING,
    LANG_MSG_MOVIE_PLAYING,
    LANG_MSG_MOVIE_STOPPED,
    LANG_ERR_MOVIE_OPEN,
    LANG_ERR_MOVIE_INVALID,
    LANG_ERR_MOVIE_VERSION,
    LANG_MSG_AVI_RECORDING,
    LANG_ERR_AVI_OPEN,
    LANG_MSG_AVI_STOPPED,

    // ---------- Genie.cpp - Game Genie ----------
    LANG_ERR_GENIE_INVALID,
    LANG_ERR_GENIE_TOO_MANY,
    LANG_MSG_GENIE_APPLIED,

    // ---------- MapperInterface.cpp ----------
    LANG_ERR_MAPPER_LOAD,
    LANG_ERR_MAPPER_NOTFOUND,
    LANG_ERR_MAPPER_VERSION,

    // ---------- Debugger.cpp ----------
    LANG_DBG_BREAK_EXEC,
    LANG_DBG_BREAK_READ,
    LANG_DBG_BREAK_WRITE,
    LANG_DBG_BREAK_ACCESS,
    LANG_DBG_BREAK_OPCODE,
    LANG_DBG_BREAK_NMI,
    LANG_DBG_BREAK_IRQ,
    LANG_DBG_BREAK_BRK,
    LANG_DBG_BREAK_SCANLINE,
    LANG_DBG_BREAK_UNDEF,
    LANG_DBG_BREAK_ENABLED,
    LANG_DBG_BREAK_DISABLED,
    LANG_MSG_DBG_LOG_STARTED,
    LANG_MSG_DBG_LOG_STOPPED,
    // ---------- Controllers device list ----------
    LANG_CONT_UNCONNECTED,
    LANG_CONT_STDCONTROLLER,
    LANG_CONT_ZAPPER,
    LANG_CONT_ARKANOIDPADDLE,
    LANG_CONT_POWERPAD,
    LANG_CONT_FOURSCORE1,
    LANG_CONT_SNESCONTROLLER,
    LANG_CONT_VSZAPPER,
    LANG_CONT_SNESMOUSE,
    LANG_CONT_FOURSCORE2,
    LANG_CONT_FAMI4PLAY,
    LANG_CONT_EXP_ARKANOIDPADDLE,
    LANG_CONT_FAMILYBASICKEYBOARD,
    LANG_CONT_SUBORKEYBOARD,
    LANG_CONT_FAMTRAINER,
    LANG_CONT_TABLET,

    // ---------- Controllers - Additional Messages ----------
    LANG_CONT_NO_CONFIG,
    LANG_CONT_ERR_DIRECTINPUT,
    LANG_CONT_ERR_KEYBOARD,
    LANG_CONT_ERR_MOUSE,
    LANG_CONT_ERR_JOYSTICK,
    LANG_CONT_ERR_KEY_ID,
    LANG_CONT_ERR_MOUSE_ID,

    // ---------- Controllers dialog ----------
    LANG_CONT_LABEL_PORT1,
    LANG_CONT_LABEL_PORT2,
    LANG_CONT_LABEL_EXP,
    LANG_CONT_CONFIG,
    LANG_CONT_UDLR,
    LANG_CONT_POV,
    
    // ---------- Common Dialogs ----------
    LANG_DLG_OK,
    LANG_DLG_CANCEL,
    LANG_DLG_YES,
    LANG_DLG_NO,
    LANG_DLG_APPLY,
    LANG_DLG_BROWSE,
    LANG_DLG_NINTENDULATOR,

    // ---------- About dialog ----------
    LANG_ABOUT_TITLE,
    LANG_ABOUT_TEXT,

    // ---------- File Submenu ----------
    LANG_MENU_FILE_HEADER,
    LANG_MENU_FILE_AUTORUN,
    LANG_MENU_FILE_BROWSESAVES,    

    // ---------- CPU Submenu ----------
    LANG_MENU_CPU_SAVESTATE,
    LANG_MENU_CPU_LOADSTATE,
    LANG_MENU_CPU_PREVSTATE,
    LANG_MENU_CPU_NEXTSTATE,
    LANG_MENU_CPU_BADOPS,
    LANG_MENU_CPU_FRAMESTEP,
    LANG_MENU_CPU_FRAMESTEP_ENABLED,
    LANG_MENU_CPU_FRAMESTEP_STEP,    
    
    // ---------- Sound Submenu ----------
    LANG_MENU_SOUND_ENABLED,

    // ---------- Debug Submenu ----------
    LANG_MENU_DEBUG_STATWND,

    // ---------- Misc Submenu ----------
    LANG_MENU_MISC_STARTAVI,
    LANG_MENU_MISC_STOPAVI,    

    // ---------- PPU Submenu ----------
    LANG_MENU_PPU_FIXASPECT,
    LANG_MENU_PPU_FRAMESKIP,
    LANG_MENU_PPU_FRAMESKIP_AUTO,
    LANG_MENU_PPU_SLOWDOWN_ENABLED,
    LANG_MENU_PPU_MODE_HYBRID,
    LANG_MENU_PPU_SIZE,
    LANG_MENU_PPU_MODE,
    LANG_MENU_PPU_PALETTE,
    LANG_MENU_PPU_SLOWDOWN,
    LANG_MENU_PPU_FULLSCREEN,
    LANG_MENU_PPU_SCANLINES,
    LANG_MENU_PPU_BILINEAR,
    LANG_MENU_PPU_INTSCALE,
    LANG_MENU_PPU_MATCHRATE,
    LANG_MENU_PPU_ALWAYSONTOP,
    LANG_MENU_PPU_EXCLUSIVEFS,
    LANG_MENU_GAME,

    // ---------- Language menu ----------
    LANG_LANG_CHANGED,
    LANG_LANG_CHANGED_MSG,

    // ---------- CPU ----------
    LANG_ERR_CPU_BAD_OPCODE,
    LANG_MSG_APU_STARTED,
    LANG_ERR_APU_REGION,
    LANG_ERR_HEADER_REOPEN,
    LANG_ERR_HEADER_OPEN,
    LANG_ERR_HEADER_NOT_INES,
    LANG_ERR_HEADER_DISKDUDE,
    LANG_ERR_HEADER_INCONSISTENT,
    LANG_TITLE_INES_EDITOR,
    LANG_ERR_CTRL_DINPUT_LEVEL,
    LANG_ERR_CTRL_DEVICE_LEVEL,
    LANG_ERR_CTRL_DEVICE_RESTORE,
    // AVI
    LANG_ERR_AVI_NOT_RECORDING,
    LANG_ERR_AVI_ALREADY_RECORDING,
    LANG_ERR_AVI_COMPRESSION,
    LANG_ERR_AVI_FRAME_NOT_RECORDING,
    LANG_ERR_AVI_WRITE_VIDEO,
    LANG_ERR_AVI_AUDIO_NOT_RECORDING,
    LANG_ERR_AVI_WRITE_AUDIO,
    // GFX
    LANG_ERR_GFX_PERF_COUNTER,
    LANG_ERR_GFX_DDRAW_DLL,
    LANG_ERR_GFX_DDRAW_ENTRY,
    LANG_ERR_GFX_DDRAW7,
    LANG_ERR_GFX_FULLSCREEN_LEVEL,
    LANG_ERR_GFX_NO_FULLSCREEN_RES,
    LANG_ERR_GFX_NO_FULLSCREEN_RES_REVERT,
    LANG_ERR_GFX_COOP_LEVEL,
    LANG_ERR_GFX_PRIMARY_SURFACE,
    LANG_ERR_GFX_SECONDARY_SURFACE,
    LANG_ERR_GFX_CREATE_SECONDARY,
    LANG_ERR_GFX_CLIPPER,
    LANG_ERR_GFX_CLIPPER_WINDOW,
    LANG_ERR_GFX_CLIPPER_ASSIGN,
    LANG_ERR_GFX_SURF_DESC,
    LANG_ERR_GFX_BIT_DEPTH,
    LANG_ERR_GFX_OPENGL,
    // MapperInterface
    LANG_ERR_MAPPER_NO_DLLS,
    // NES
    LANG_ERR_NES_RELOCATE,
    LANG_ERR_GFX_FLIP,
    LANG_ERR_GFX_ILLEGAL_PALETTE,
    LANG_ERR_GFX_LOAD_PALETTE,
    LANG_ERR_GFX_INVALID_PALETTE,
    LANG_DLG_CTRL_STDCONT,
    LANG_DLG_CTRL_BUTTONS,
    LANG_DLG_CTRL_DPAD,
    LANG_DLG_CTRL_A,
    LANG_DLG_CTRL_B,
    LANG_DLG_CTRL_SELECT,
    LANG_DLG_CTRL_START,
    LANG_DLG_CTRL_UP,
    LANG_DLG_CTRL_DOWN,
    LANG_DLG_CTRL_LEFT,
    LANG_DLG_CTRL_RIGHT,
    LANG_DLG_CTRL_TRIGGER,
    LANG_DLG_CTRL_AXIS,
    LANG_DLG_CTRL_ZAPPER,
    LANG_DLG_CTRL_ARKPAD,
    LANG_DLG_CTRL_POWERPAD,
    LANG_DLG_CTRL_FOURSCORE,
    LANG_DLG_CTRL_FAMI4PLAY,
    LANG_DLG_CTRL_SNESCONT,
    LANG_DLG_CTRL_SNESMOUSE,
    LANG_DLG_CTRL_VSZAPPER,
    LANG_DLG_CTRL_FLIP,
    LANG_DLG_CTRL_PORT1,
    LANG_DLG_CTRL_PORT2,
    LANG_DLG_CTRL_PORT3,
    LANG_DLG_CTRL_PORT4,
    LANG_DLG_CTRL_CONFIG,
    LANG_DLG_CTRL_CLOSE,
    LANG_DLG_CTRL_TITLE,
    LANG_DLG_CTRL_MORE_BUTTONS,
    LANG_DLG_CTRL_FAMTRAIN,
    LANG_DLG_CTRL_FBKEY,
    LANG_DLG_CTRL_TABLET,
// Sound Volume
    LANG_DLG_VOL_MASTER,
    LANG_DLG_VOL_SQ0,
    LANG_DLG_VOL_SQ1,
    LANG_DLG_VOL_TRI,
    LANG_DLG_VOL_NOI,
    LANG_DLG_VOL_PCM,
    LANG_DLG_VOL_EXT,
    LANG_DLG_VOL_MUTE,
    LANG_DLG_VOL_CLOSE,
// iNES Header Editor
    LANG_DLG_INES_TITLE,
    LANG_DLG_INES_FILENAME,
    LANG_DLG_INES_VER1,
    LANG_DLG_INES_VER2,
    LANG_DLG_INES_MAPPER,
    LANG_DLG_INES_PRG,
    LANG_DLG_INES_CHR,
    LANG_DLG_INES_HORIZ,
    LANG_DLG_INES_VERT,
    LANG_DLG_INES_VS,
    LANG_DLG_INES_PC10,
    LANG_DLG_INES_4SCR,
    LANG_DLG_INES_BATT,
    LANG_DLG_INES_TRAIN,
    LANG_DLG_INES_SUBMAP,
    LANG_DLG_INES_BATTERY,
    LANG_DLG_INES_PRGRAM,
    LANG_DLG_INES_CHRRAM,
    LANG_DLG_INES_NTSC,
    LANG_DLG_INES_PAL,
    LANG_DLG_INES_DUAL,
    LANG_DLG_INES_VSPPU,
    LANG_DLG_INES_VSFLAGS,
    // Movie dialogs
    LANG_DLG_MOVIE_PLAY_TITLE,
    LANG_DLG_MOVIE_RECORD_TITLE,
    LANG_DLG_MOVIE_FILE,
    LANG_DLG_MOVIE_DESC,
    LANG_DLG_MOVIE_LENGTH,
    LANG_DLG_MOVIE_FRAMES,
    LANG_DLG_MOVIE_RERECORDS,
    LANG_DLG_MOVIE_TVMODE,
    LANG_DLG_MOVIE_RESUME,
    LANG_DLG_MOVIE_CONTROLLERS,
    LANG_DLG_MOVIE_PORT1,
    LANG_DLG_MOVIE_PORT2,
    LANG_DLG_MOVIE_EXPANSION,
    LANG_DLG_MOVIE_CONFIGURE,
    LANG_DLG_MOVIE_RECORD_FROM,
    LANG_DLG_MOVIE_HARD_RESET,
    LANG_DLG_MOVIE_CUR_STATE,
    // Palette dialog
    LANG_DLG_PAL_TITLE,
    LANG_DLG_PAL_PALETTE,
    LANG_DLG_PAL_HUE,
    LANG_DLG_PAL_SAT,
    LANG_DLG_PAL_CUSTOM,
    LANG_DLG_PAL_PREVIEW,
    LANG_DLG_PAL_EMPHASIS,
    LANG_DLG_PAL_NOTE,
    LANG_DLG_PAL_EXTRAGRAY,
    // DLL Select dialog
    LANG_DLG_DLL_TITLE,
    LANG_DLG_DLL_TEXT,
    // Breakpoint dialog
    LANG_DLG_BREAK_TITLE,
    LANG_DLG_BREAK_ENABLED,
    LANG_DLG_BREAK_ADDR,
    LANG_DLG_BREAK_OP,
    LANG_DLG_BREAK_TIME,
    LANG_DLG_BREAK_EXEC,
    LANG_DLG_BREAK_READ,
    LANG_DLG_BREAK_WRITE,
    LANG_DLG_BREAK_ACCESS,
    LANG_DLG_BREAK_OPCODE,
    LANG_DLG_BREAK_NMI,
    LANG_DLG_BREAK_IRQ,
    LANG_DLG_BREAK_BRK,
    LANG_DLG_BREAK_SCANLINE,
    LANG_DLG_BREAK_FROM,
    LANG_DLG_BREAK_TO,
    LANG_DLG_DEBUG_TITLE,
    // Debugger CPU dialog
    LANG_DLG_DBGCPU_TITLE,
    LANG_DLG_DBGCPU_REGISTERS,
    LANG_DLG_DBGCPU_TIMING,
    LANG_DLG_DBGCPU_IRQS,
    LANG_DLG_DBGCPU_FLAGS,
    LANG_DLG_DBGCPU_BANKS,
    LANG_DLG_DBGCPU_BREAKPOINTS,
    LANG_DLG_DBGCPU_CONTROLS,
    LANG_DLG_DBGCPU_MEMORY,
    LANG_DLG_DBGCPU_TRACE,
    LANG_DLG_DBGCPU_RUN,
    LANG_DLG_DBGCPU_STEP,
    LANG_DLG_DBGCPU_RESET,
    LANG_DLG_DBGCPU_POWER,
    LANG_DLG_DBGCPU_DUMPCPU,
    LANG_DLG_DBGCPU_DUMPPPU,
    LANG_DLG_DBGCPU_STARTLOG,
    LANG_DLG_DBGCPU_STOPLOG,
    LANG_DLG_DBGCPU_SEEKPC,
    LANG_DLG_DBGCPU_SEEKTO,
    LANG_DLG_DBGCPU_SEEKSEL,
    LANG_DLG_DBGCPU_ADD,
    LANG_DLG_DBGCPU_EDIT,
    LANG_DLG_DBGCPU_DELETE,
    // Debugger PPU dialog
    LANG_DLG_DBGPPU_TITLE,
    LANG_DLG_DBGPPU_NAMETABLE,
    LANG_DLG_DBGPPU_SPRITES,
    LANG_DLG_DBGPPU_PATTERNS,
    LANG_DLG_DBGPPU_PALETTE,
    LANG_DLG_DBGPPU_DETAILS,
    LANG_DLG_DBGPPU_CLICK,
    LANG_DLG_DBGPPU_HOVER,
    LANG_DLG_DBGPPU_SELTYPE,
    LANG_DLG_DBGPPU_TILEFLIP,
    LANG_ERR_MAPPER_DLL_VERSION,
    LANG_ERR_MAPPER_DLL_LOAD,
    // Theme
    LANG_MENU_PPU_THEME,
    LANG_MENU_PPU_THEME_LIGHT,
    LANG_MENU_PPU_THEME_DARK,

    // ---------- File dialog filter display names ----------
    LANG_FILTER_ROM_ALL,
    LANG_FILTER_ROM_INES,
    LANG_FILTER_ROM_UNIF,
    LANG_FILTER_ROM_FDS,
    LANG_FILTER_ROM_NSF,
    LANG_FILTER_ROM_INES_SHORT,
    LANG_FILTER_MOVIE,
    LANG_FILTER_AVI,
    LANG_FILTER_PALETTE,
    LANG_OPEN_HEADER_TITLE,

    // ---------- Language menu ----------
    LANG_NO_LANGUAGES,

    // ---------- Movie ----------
    LANG_MOVIE_UNEXPECTED_EOF,
    LANG_MOVIE_TV_PAL,
    LANG_MOVIE_TV_NTSC,
    LANG_MOVIE_LENGTH_FMT,

    // ---------- Debugger validation ----------
    LANG_DBG_INVALID_ADDR,
    LANG_DBG_INVALID_OPCODE,
    LANG_DBG_INVALID_SCANLINE,

    // ---------- MapperInterface compatibility ----------
    LANG_COMPAT_UNSUPPORTED,
    LANG_COMPAT_PARTIAL,
    LANG_COMPAT_MOSTLY,
    LANG_COMPAT_FULL,

    LANG_STRING_COUNT
};

#define LANG_MAX_STRING 1024

namespace Lang
{
    void Init(HINSTANCE hInst);
    bool Load(const TCHAR *langName);
    const TCHAR* GetString(LangStringID id);
    int GetLanguageCount();
    const TCHAR* GetLanguageFileName(int index);
    const TCHAR* GetLanguageDisplayName(int index);
    const TCHAR* GetCurrentLanguage();
    void UpdateMenu(HMENU hMenu);
    void SaveToRegistry(const TCHAR *langName);
    std::wstring LoadFromRegistry();
}
