name: Build NintendulatorML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        platform: [Win32, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build project (v143)
      run: |
        msbuild msvc140/Nintendulator.vcxproj `
          /p:Configuration=Release `
          /p:Platform=${{ matrix.platform }} `
          /p:PlatformToolset=v143 `
          /p:WindowsTargetPlatformVersion=10.0 `
          /p:UseEnv=true

    - name: Create release folder
      run: |
        New-Item -ItemType Directory -Force -Path release

    - name: Copy executable + files
      run: |
        Copy-Item "msvc140/${{ matrix.platform }}/Release/*.exe" release/ -Force
        Get-ChildItem -Recurse *.dll | Copy-Item -Destination release/ -Force
        Copy-Item Lang release/Lang -Recurse -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NintendulatorML-${{ matrix.platform }}
        path: release
